- speckle/logging/exceptions.py
Exceptions returned from `make_request()` were not being shown to the user as the `__repr__` override was not affecting the printed string representation. This meant the response to a failed request was just...nothing. Oops! Fixed this here by changing the `__repr__` overrides to `__str__` overrides
do classes no longer default to the `__repr__` override?
to investigate...
> 🏮 fix(exceptions): add string override

- speckle/serialization/base_object_serializer.py
- speckle/transports/abstract_transport.py
- speckle/transports/memory.py
- speckle/transports/server.py
This PR implements the `ServerTransport` which can be used on it's own or through `operations.send()` and `operations.receive()`. 
See transports in `speckle-sharp/Core` and this [forum post](https://discourse.speckle.works/t/core-2-0-transports/919) for more information about transports.
> 🏄‍♀️ Server transport

- speckle/transports/abstract_transport.py
- speckle/transports/memory.py
- speckle/transports/server.py
- speckle/transports/sqlite.py
default values can no longer be unintentionally mutated and the following should now return the expected results
```py
mem_a = MemoryTransport()
mem_b = MemoryTransport()
mem_a.objects = {"a": 123, "b": 456}
print(mem_a.objects)  # {"a": 123, "b": 456}
print(mem_b.objects)  # {}
```
resolves #19
> refactor(transports): inherit from `BaseModel`

- speckle/transports/abstract_transport.py
…Transport
Python type hint evaluation can be defferred by enclosing the type hint in quotes. This renders the
Transport class useless, while still keeping the functionality. Plus you asked for it :D
> refactor(abstract_transport): add deferred type hints

- speckle/api/operations.py
- speckle/objects/__init__.py
- speckle/objects/base.py
- speckle/objects/mesh.py
- speckle/serialization/base_object_serializer.py
- speckle/transports/memory.py
Recently, a new feature was introduced in `speckle-sharp` - chunking! This allows you to "chunk" long unmanageable lists into smaller `DataChunks` that can be detached and sent separately to avoid a clunky and memory intensive serialisation process (think serialising a list of points or surfaces thousands and thousands of items long!). This is the python implementation of the same functionality.
To use this in an object, you simply populate the new `_chunkable` dict with the name of your chunkable prop as the key and the max chunk size as the value.
```py
CHUNKABLE_PROPS = {
"vertices": 2000,
"faces": 2000,
"colors": 2000,
"textureCoordinates": 2000,
}
class Mesh(Base):
vertices: List[float] = None
faces: List[int] = None
colors: List[int] = None
textureCoordinates: List[float] = None
def …
```
> 🍰 Chunking of long lists

- speckle/objects/base.py
- speckle/serialization/base_object_serializer.py
This intercepts `__setattr__` to allow `@property.setter` to work as expected. Serialisation has also been modified to account for props on deserialisation.
> 🥠 Support for properties

- .vscode/launch.json
- speckle/objects/base.py
- tests/test_base.py
enforces rules for `Base` attribute names
- no empty strings (includes `""` and `"@"`)
- no invalid characters: currently list is just `['.', '/']`
- no more than one leading `@`
related to specklesystems/speckle-sharp#37
> ☑ Base Attribute Name Validation

- speckle/api/operations.py
- speckle/serialization/base_object_serializer.py
This removes extra checks that were needed due to a bug in server. Tests will fail as the test server has not been updated to reflect these changes. This will be merged once the test server is up to date.
related to specklesystems/speckle-server#78
fixed in specklesystems/speckle-server@aca61b8
> 🧺 Trash the workarounds in ops and serialiser for `speckle_type` vs `speckleType`

- README.md
* Add some import to make origin of objects / module used explicit
* Fix #L118:
```python
In [46]: received_base = client.object.get(hash)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-46-8171539461b3> in <module>
----> 1 received_base = client.object.get(hash)
TypeError: get() missing 1 required positional argument: 'object_id'
```
> Add infos and fix to README.md

- speckle/serialization/base_object_serializer.py
- tests/test_serialization.py
- don't overwrite `speckle_type` when receiving unknown object
- check for empty lists on deserialisation
- explicit none check for ignored vals on serialisation
(was unintentionally ignoring `0`s)
- test for unknown type deserialisation
some of this will change w/ #58, 
but needed to merge the fixes for a demo tomorrow
> 🐛 fix(serialiser): smol bug fixes

- speckle/api/operations.py
- speckle/objects/base.py
- speckle/objects/point.py
- speckle/serialization/base_object_serializer.py
- base object `get_member_names` now returns attributes _and_ properties
- all properties are now included in serialisation
- properties without setters will be ignored upon deserialisation
> 🥠 feat(base): support serialisation of all properties

- speckle/serialization/base_object_serializer.py
- tests/conftest.py
- tests/test_serialization.py
oopsie - lists were not being detached properly before. this fixes the issue so dynamically and statically defined detached lists will detach the base objects within the list and leave all other object types as they are. eg, the following attribute:
```py
base["@stuff"] = [Base(), 42, "wow"]
```
will create a list with one reference object, but leave `42 , "wow"` as they are in the list
> fix(serializer): detached lists

- speckle/objects/base.py
- speckle/objects/fakemesh.py
- speckle/objects/geometry.py
adds helper methods on `Base` that can be called in the constructors
to prevent ppl messing this up when defining their own objects
> feat(base): improve adding chunkables/detachables

- speckle/objects/base.py
would bork in other connectors with name as just `DataChunk`
> fix(base): specify full name for datachunk

- .circleci/config.yml
- tests/conftest.py
As discussed, all tests are now wired up to run against `localhost:3000`.
CI config now spins up a new speckle server in the same way we're doing so for .Net
Python tests should be run against your own local server if needed.
> ci: Spin-up new server for each test run

- tests/test_branch.py
- tests/test_commit.py
after many `console.log`s, I realised the real issue was that I was sharing objects across streams. due to cristi's new security patches, this is no longer possible! oopsies, all fixed now 😊
closes #83
> Fix failing tests

- specklepy/serialization/base_object_serializer.py
couldn't replicate #88 but i found this error w the stuff i was trying to receive when i dug a bit deeper, so maybe it was related? happened w a rhino 7 commit - wasn't handled before bc from what I understood we were not serialising nulls.
> fix(serializer): handle receiving `None` vals

- specklepy/api/resources/__init__.py
This fix the issue #96 on my system but you might want to test on Windows too.
This modification was inspired by: https://stackoverflow.com/questions/3365740/how-to-import-all-submodules
> Fix: path process error on Linux #96

- specklepy/api/client.py
as alan noted, the default one is garbo lol
hopefully this will make it clearer for users
> docs(client): add dosctring to the `SpeckleClient`

- specklepy/objects/base.py
- specklepy/objects/units.py
noticed thanks to the forum: `@property` attributes were serialising fine, but parent props on children were not getting picked up
> fix(base): get parent props on child serialisation 

- .circleci/config.yml
- specklepy/api/client.py
- specklepy/api/credentials.py
- specklepy/logging/exceptions.py
- specklepy/transports/server/server.py
- tests/test_wrapper.py
- parse any url into a stream wrapper
- get the type of the wrapper in the same way as in .net
- `get_client` and `get_transport` methods for ez retrieval of these with local acct based on the wrapper contents
- tests for this
closes #112
> 🌯 Stream Wrapper with Client & Server Transport helper methods

- poetry.lock
- pyproject.toml
- specklepy/api/credentials.py
- specklepy/api/operations.py
- specklepy/api/resource.py
- specklepy/api/resources/commit.py
- specklepy/objects/base.py
- specklepy/objects/fakemesh.py
- specklepy/objects/geometry.py
- specklepy/serialization/base_object_serializer.py
- tests/conftest.py
- tests/test_base.py
- tests/test_objects.py
- tests/test_serialization.py
- removes pydantic from the `Base` and the object models 
- pydantic is still used for the api models
- lightweight type checking is enforced by caching type hints on the class def
- we check basic types and generic `typing` types, but we don't check subscripted types within generics (eg `List[str]` will only be checked as list
- typing stuff is inconsistent between 3.6, 3.7, and 3.8 so needa be careful here
tests with [speckle haus](https://speckle.xyz/streams/3073b96e86/commits/604bea8cc6) and creating objects
| branch  | serialize haus | deserialize haus | 100k objs (benchmark) | 100k `Point` | 100k `Box` |
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
| `main`  | 29.6 sec | 27.4 sec | 0.01 sec | 1.70 sec | 14.2 sec |
| …
> feat(base): remove pydantic and roll our own type checking

- specklepy/api/models.py
- specklepy/api/resources/commit.py
thanks morten for spotting this!
- adds the `branchName` to `commits.list` query
- adds `branchName` to the commit model `repr` for funsies - it's prob nice to see there 
closes #142
> fix(client): add `branchName` to commits query

- specklepy/objects/base.py
- specklepy/objects/units.py
- tests/test_base.py
https://speckle.community/t/bug-when-receiving-revit-data-in-python-speckle-client/2168
> fix(units): warn and don't set for invalid args

- specklepy/serialization/base_object_serializer.py
- tests/test_serialization.py
fall back on standard json lib when ujson fails due to big int 
closes #152 and https://github.com/specklesystems/speckle-blender/issues/74
> fix(serializer): ujson big int issue

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .devcontainer/docker-compose.yaml
This makes it easier to develop and run tests against an environment that has the right python virtualenv + a local speckle server + postgres + redis instance/
You can get started in VSCode by using `CTRL + SHIFT + P` (or something else on Max I guess :upside_down_face: ). You can find more info about VSCode devcontainers and how to use them [here](https://code.visualstudio.com/docs/remote/create-dev-container).
> chore(dev): add devcontainer configuration

- specklepy/transports/server/server.py
objects were being split on non-english characters causing receive fails
will also get fixed server side, but this will act as a double check
and an immediate fix for people dealing with this now
> feat(server): force utf-8 encoding

- specklepy/api/wrapper.py
used for creating a transport if you don't have a local account
for the specified server
> fix(wrapper): use full url for creating shell account

- specklepy/api/client.py
- specklepy/api/resources/server.py
- specklepy/logging/metrics.py
- add py version to metrics to ensure it's safe to drop 3.6 support
- add metrics for client init / auth
- add server metrics
- remove incompatible server check in client
(at this point, it's been long enough that I think it's fine and will
save time on request / esp in places like blender)
> feat(metrics): some cleanup and updates

- specklepy/logging/metrics.py
some environments may throw an error when trying to `socket.gethostbyname`. not sure exactly what kind of env this would be, but it was reported here
https://speckle.community/t/specklepy-get-default-account-error/3085
however, the prop this is used for `user_ip` is no longer needed in the metrics request so i think it's easier and cleaner to just remove it
> fix(metrics): remove unused prop

- specklepy/objects/base.py
- specklepy/objects/units.py
change in sharp that wasn't propagated to py!
also fix resulting encoding issue without a default unit
> fix(base): remove default units to `Base`

- specklepy/transports/server/server.py
when calling `copy_objects_and_children`, target transport needs to be notified of begin and end write
> fix(transport): call begin/end write in server

- specklepy/api/credentials.py
- specklepy/serialization/base_object_serializer.py
- specklepy/transports/sqlite.py
due to metrics, this would sometimes cause a warning with the sqlite transport trying to be closed on a different thread (as it was getting cleaned up by `__del__`). to resolve this, the sqlite transport is now closed directly after use in `get_local_accounts()`
> fix(credentials): clean up sqlite transport directly after getting accts

- specklepy/objects/base.py
#197 Sorts the serializable attributes before they are returned from
.get_serializable_attributes(). Prevents the object id to change if the
order of the member names from .get_member_names() changes.
> feat(base): sort serializable attributes

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .devcontainer/docker-compose.yaml
- specklepy/api/client.py
- specklepy/api/credentials.py
- specklepy/api/models.py
- specklepy/api/resource.py
- specklepy/api/resources/__init__.py
- specklepy/api/resources/branch.py
- specklepy/api/resources/commit.py
- specklepy/api/resources/object.py
- specklepy/api/resources/server.py
- specklepy/api/resources/stream.py
- specklepy/api/resources/subscriptions.py
- specklepy/api/resources/user.py
- specklepy/logging/exceptions.py
- specklepy/logging/metrics.py
- specklepy/objects/base.py
- tests/conftest.py
- tests/test_base.py
- tests/test_server.py
- tests/test_stream.py
adds support for new stream invite flow that is being introduced on Speckle Server >= 2.6.4 (double check this)
this includes additions to `stream` including:
- `get_all_pending_invites`
- `get_pending_invite`
- `invite`
- `invite_batch`
- `invite_cancel`
- `invite_use`
- `update_permission`
and test for all of these
main changes are here:
https://github.com/specklesystems/specklepy/pull/202/files#diff-fac1f2e2b8f6d92364d9669dcc6e87686845c6ba33a2de2a0cfb8e071e99f637
tests are here:
https://github.com/specklesystems/specklepy/pull/202/files#diff-ea0709cafe72641d2626e0ac259bd85f09f16496ba240cee1e25589f64ced848
to check:
- query from within the stream endpoint!
- correct, for now only admins can batch invite
closes #201 and more!
similar thing may need to happen here …
> feat(client): stream invites

- specklepy/logging/metrics.py
so apparently in jupyter notebooks this will actually throw
unlike in a regular python environment.
changing severity to debug since no one should ever care except me
when i'm debugging lol! srry
https://speckle.community/t/error-sending-metrics-request/3405
> fix(metrics): log ex as debug for jupyter notebook

- pyproject.toml
In #228 `specklepy.transports.abstract_transport` changed `from pydantic.main import Extra` to `from pydantic.config import Extra`. This change requires `pydantic>=1.9`.
Updates the minimum required version of `pydantic` given in `pyproject.toml` to `pydantic^1.9`.
> fix: update minimum required version of pydantic

- poetry.lock
- pyproject.toml
- src/specklepy/objects/base.py
- src/specklepy/objects/structural/__init__.py
- src/specklepy/objects/structural/materials.py
- src/specklepy/objects/structural/properties.py
- tests/test_registering_base.py
- tests/test_structural.py
- tests/test_traverse_value.py
use a dotnet `FullName` like behavior to deremine the speckle_type
fixes #231
fixes #221
> feat(Base): rework speckle_type handling to better align with Core

- src/specklepy/objects/structural/properties.py
Fix: Typo fix of `STRUCTURAL PROPERTY` variable in https://github.com/specklesystems/specklepy/blob/main/src/specklepy/objects/structural/properties.py#L8
Tiny bug with big consequences. All property objects will not be properly recognized and will be deserialized to a `Base` object. This gives issues in further conversion for our case, where we convert an analytical Revit model from Speckle to Python.
Fix typo
Nothing, as far as I can see, **small patch would be much appreciated!** :)
Fixed the typo locally, which allows me to convert a full structural model from Speckle to Python. I tested with a stream of an analytical Revit model used in of your tutorials: https://speckle.xyz/streams/bf8c36d0d2/commits/68269d458f
-->
> Typo fix in properties.py

- src/specklepy/api/models.py
- src/specklepy/objects/structural/axis.py
- src/specklepy/objects/structural/properties.py
Update `speckle_type` of `SectionProfile` to match C#, update type hints with C# Enum values to int.
For the SectionProfile, a separate static variable e.g. STRUCTURAL_PROFILE could be created later, I now just made an easy fix. For the enumeration attributes, I believe they should be integer, as e.g. Revit pushes them as integers, not strings.
Section profile fix allows to properly deserialize `SectionProfile` objects.
The type hint fixes allow to properly receive the `Axis` and `Activity` objects.
Deserialized Analytical Revit test streams with the proposed changes, which then works.
> Fix: Interoperability from Revit analytical to specklepy structural

- src/specklepy/objects/structural/__init__.py
- src/specklepy/objects/structural/axis.py
We encountered a bug where in Speckle, the AxisType is set as 0, so an `int`, but when we try to receive this commit in `specklepy`, we get the following error: 
`SpeckleException: Cannot set 'Axis.axisType':it expects type 'typing.Optional[str]',but received type 'int'`
I'm not sure why it would ever be string actually. It should be an Enum. For `LoadAxisType`, this is implemented correctly, so I have implemented it almost the same way for `Axis`. 
This error showed up when we switched from using a lot of our own custom Speckle structural classes to those that have been added to `specklepy`.
We really need this fix to be able to retrieve anything in Speckle at this point, so it would be great if it could be merged and released relatively soon.
- Added AxisType Enum class in `axis.py`.
- …
> Fix: Add AxisType and fix its type in Axis

- src/specklepy/api/resources/stream.py
stream.invite_batch allows for a list of emails or user_ids to be invited to a stream. The existing code doesn't check for the default None type prior to the conversion of each to user invite objects
each List builder `user_invites` and `email_invites` includes a None type check before iteration. 
The existing code was seemingly performing the None check on each list as a filter. This fails as the list iteration is already attempted before hitting the filter.
> fix: `invite_batch` failing where `emails` or `user_ids` is not provided

- src/specklepy/objects/base.py
- tests/unit/test_type_validation.py
Currently an error is raised in below line, when an attempt is made to convert a given value to a float. In my case, this is a problem when I have a Union type hint that includes float, e.g. `Union[int, float, dict]`. During type checking, an iteration will be made over the types within the Union. Then, when the value is a dictionary, it will give a TypeError, which is currently not suppressed by the `contextlib.suppress()` call.
https://github.com/specklesystems/specklepy/blob/420c73f4844d124b1a813b16a2a2ee71a521bccd/src/specklepy/objects/base.py#L312
I agree that this Union type hint with both numeric types and a dictionary is not very common, but it still shouldn't give an error. By also suppressing TypeError, this is prevented.
TypeError is also suppressed. This will suppress the …
> Fix: also suppress TypeError during type checking.

- pyproject.toml
- src/speckle_automate/automation_context.py
- src/speckle_automate/runner.py
- tests/intergration/speckle_automate/test_automation_context.py
> fix: report relative url for context view

- .pre-commit-config.yaml
- pyproject.toml
- src/speckle_automate/runner.py
> feat: read automation function inputs from file

- src/specklepy/objects/GIS/layers.py
Uses the `typing.Dict` intead of `dict` to annotate `renderer` in `objects.GIS.layers.Layer` to be compatible with <3.9.
> fix: dict type of renderer in Layer

- src/specklepy/core/api/client.py
> feat: fix authenticate with token mechanism

- src/specklepy/core/api/credentials.py
- src/specklepy/core/api/models.py
- src/specklepy/core/api/wrapper.py
- tests/unit/test_account_server_migration.py
Added server migration properties to server info
Added new function in `Credentials.py` `get_account_for_server(host: str)`
Added unit test (mimicking the C# one) to test above function
Equivalent to the https://github.com/specklesystems/speckle-sharp/pull/3201 and https://github.com/specklesystems/speckle-sharp/pull/3216
> feat(core): [CNX-9108] Added server migration support

- .devcontainer/Dockerfile
- src/specklepy/api/resources/active_user.py
- src/specklepy/api/resources/other_user.py
In the User Resource class documentation and method docstrings, the changes include:
1. Clarification of Method Purposes: Each method's docstring now clearly states its purpose and the context in which it should be used. 
2. Detailed Parameter Descriptions: Each method's argument parameters are now explicitly described, including their data types and whether they are optional. 
3. Return Value Descriptions: The expected return values for each method are now properly documented.
4. Correction of Typos and Inaccuracies: Any typos, inaccuracies, or misleading information in the original docstrings have been corrected to ensure the documentation accurately reflects the functionality of the Resource class.
> Corrects and enhances user API class documentation (CNX-9172)

- src/specklepy/core/api/client.py
Fixes #336 
Expose the `timeout` argument from the underlying `RequestsHTTPTransport` to `SpeckleClient`
> Feature: adds connection_timeout argument to SpeckleClient

- src/speckle_automate/automation_context.py
- src/speckle_automate/runner.py
- src/speckle_automate/schema.py
> feat: add excetion outcome reporting to functions

- src/specklepy/api/client.py
- src/specklepy/api/wrapper.py
- src/specklepy/core/api/client.py
- src/specklepy/core/api/wrapper.py
- tests/integration/conftest.py
- tests/integration/test_stream.py
- tests/integration/test_wrapper.py
The new default domain for Speckle is app.speckle.systems. We are in the process of deprecating speckle.xyz
https://linear.app/speckle/project/deprecate-fe1-47acf8176ef9/overview
- also updates the example email domain to use the IANA owned example domain instead of a production or random domain
> feat(default domain): app.speckle.systems is now default over speckle.xyz

- src/speckle_automate/automation_context.py
- Calls of `automate_context.store_file_result()` would fail for functions with the following error:
```
Client error '404 Not Found' for url 'https://latest.speckle.systems//api/stream/<streamId>/blob'
```
- This is because `automation_run_data.speckle_server_url` was being set with a trailing slash by Automate (e.g. `https://latest.speckle.systems/`) and the sdk appends `/api/stream` to that.
- Changes url construction here (instead of Automate)
> fix(automate): remove extra slash

- src/specklepy/core/api/inputs/version_inputs.py
- tests/integration/client/current/test_version_resource.py
A breaking change was made to our GraphQL api to require project ids on the VersionUpdate, VersionMoveToModel, and VersionDelete inputs.
This PR updates the python SDK with this change
> Updated version mutation inputs

- src/speckle_automate/automation_context.py
- src/speckle_automate/schema.py
- Object results currently mirror log levels, but are used to report pass/fail information about collections of objects. Some users (@bjoernsteinhagen ) have requested the ability to also surface more information about "success" results with them.
- Frontend will fall back to `INFO` styling, or use new styling ones specklesystems/speckle-server#3537 merged
- Adds `SUCCESS` to enum and util like the others
> fix(automate): add success result case

- src/speckle_automate/automation_context.py
- We need to submit function run statuses with a project id now
- Luckily it was already here in the automate context
*THIS IS A BREAKING CHANGE* and will require re-deploys of existing functions (we should delete all existing functions). This will not be merged or released until everyone else is ready.
> fix(automate): include project id in run reporting

- src/specklepy/core/api/resources/deprecated/stream.py
Blender connector relies on this function
> updated active user streams

- src/speckle_automate/automation_context.py
- We had an issue today where .env values were being cached (?) somewhere. SDK calls to `receive_version()` failed because it was using ids that didn't match the latest configuration.
- This was unclear because the error message was unhelpful
- This is likely to happen when setting up test automations and so we can improve the message
- Adds details about which specific version we attempted to receive when failing
> chore(automate): improve error message when version receive fails

- src/speckle_automate/automation_context.py
- src/specklepy/api/resources/current/version_resource.py
- src/specklepy/core/api/credentials.py
- src/specklepy/core/api/inputs/model_inputs.py
- src/specklepy/core/api/inputs/project_inputs.py
- src/specklepy/core/api/inputs/user_inputs.py
- src/specklepy/core/api/inputs/version_inputs.py
- src/specklepy/core/api/models/current.py
- src/specklepy/core/api/models/graphql_base_model.py
- src/specklepy/core/api/models/subscription_messages.py
- src/specklepy/core/api/resources/current/active_user_resource.py
- src/specklepy/core/api/resources/current/model_resource.py
- src/specklepy/core/api/resources/current/project_invite_resource.py
- src/specklepy/core/api/resources/current/project_resource.py
- src/specklepy/core/api/resources/current/server_resource.py
- src/specklepy/core/api/resources/current/version_resource.py
- src/specklepy/objects/__init__.py
- tests/integration/client/current/test_active_user_resource.py
- tests/integration/client/current/test_model_resource.py
- tests/integration/client/current/test_project_invite_resource.py
- tests/integration/client/current/test_project_resource.py
- tests/integration/client/current/test_subscription_resource.py
- tests/integration/client/current/test_version_resource.py
- tests/integration/client/deprecated/test_stream.py
- tests/integration/conftest.py
- tests/integration/speckle_automate/test_automation_context.py
- tests/unit/test_account_server_migration.py
- uv.lock
Updated automate SDK to use new FE2 API
There's only a couple changes:
`create_new_version_in_project` no longer uses a `branchName` instead `modelId`.
Because of this also, it will not create a branch for the user if one doesn't already exist.
To cover this usecase, I've added `create_new_model_in_project` and `get_model` to create a model with the given inputs.
---
Additional, under @gjedlicska 's suggestion, I have updated the graphql object models to use snake_casing, and using a pydantic alias config to ensure json serialization using camelCasing.
<details>
<summary>Discussed questions</summary>
<br>
1. should `create_new_model_in_project` try and find a model with the existing name and return that? right now it will throw `SpeckleException`
2. <strike>`create_new_version_in_project` …
> Update Automate to use FE2 API

- docker-compose.yml
Updates docker compose file to include the required redirect env var
Same fix applied to https://github.com/specklesystems/speckle-sharp/pull/3690
> fic(ci): docker compose file missing frontend origin env var

- .github/workflows/publish.yml
The changes made in this commit https://github.com/specklesystems/specklepy/commit/adc0c40ab7e7803f1ac20f015d40c72e6373c3cb
don't appear to work, the publish workflow has not triggered since this change was introduced.
To unblock Kate, I will revert this back to run publish on all pushes to v3 dev
We can decide later once @gjedlicska is back what we want to do with this publish workflow
> Publish to testpypi every push

- src/specklepy/core/api/models/current.py
The graphql schema was updates in server version 2.23 to return a `null` reference object id on versions when the version history limit has been exceeded.
> feat(api): Updated Version class with schema change to allow null reference object id when version history has been exceeded

- src/specklepy/core/api/resources/current/active_user_resource.py
There was a mistake in https://github.com/specklesystems/specklepy/pull/409
For all gql variables, we need to explicitly serialize strings
> Correct filter serialization

- src/specklepy/core/api/resources/current/active_user_resource.py
One more place I forgot to add the creation state to a workspace query
Because we don't have integration tests for the workspace queries, this slipped through.
@bimgeek this should fix the problem you're seeing in Blender
> fic(api): Fix mistake in workspace queries

- src/specklepy/core/api/models/current.py
- src/specklepy/core/api/resources/current/project_resource.py
centralized `can_load` and `can_publish` permission checks to not to do same operation in every connector.
> feat: adds `can_load` and `can_publish` permission checks

- src/specklepy/api/resources/current/active_user_resource.py
- src/specklepy/core/api/models/current.py
- src/specklepy/core/api/resources/current/active_user_resource.py
Update the `client.active_user.get_active_workspace` function in response to a breaking change on the server.
> fix(api)!: `get_active_workspace` now returns a `LimitedWorkspace`

- src/speckleifc/__main__.py
- src/speckleifc/importer.py
- src/speckleifc/main.py
Implemented the changes we discussed @gjedlicska @clairekuang for the IFC importer
This PR adds Mixpanel Send event tracking to the IFC Importer
It also changes the slug reported to the `VersionCreate` from `"IFC"` to `"ifc"` to align with the ifc slug.
Note... I'm not doing any `ifc-ifcopenshell-importer` slugs, as this would be a breaking change as far as historical IFC metrics is concerned, and also doesn't really offer value so long as our IFC importer only converts ifc files...
see https://github.com/specklesystems/speckle-sharp-connectors/pull/1063
> feat(speckleifc): Add Metrics tracking

- src/specklepy/transports/server/batch_sender.py
There was a mistake in one of our calls to the logger that was generating lots of warnings when running the ifc import service
```
File "/app/lib/python3.13/site-packages/specklepy/transports/server/batch_sender.py", line 125, in _bg_send_batch
LOG.info(
Message: 'Uploading batch of {batch_size} objects {new_object_count}: '
Arguments: ('(size: {upload_size}, compressed size: {upload_data_size})', {'batch_size': 2, 'new_object_count': 2, 'upload_size': 944518, 'upload_data_size': 67254})
```
> Fix log warnings caused by mistake in args

- src/speckleifc/property_extraction.py
We got some alerts of a flood of 400 errors triggered by IFC uploads.
I believe this is caused by `NaN` values being sent to the server.
js and python disagree with how to serialize NaN values, so the server was handling the post requests to `/objects/:streamId` as invalid json.
In this PR, for IFC values that we know may be NaN,  I'm mapping them to `None` values.
This follows the js standard of mapping to `null` value
The python standard is to serialize them as a `NaN` keyword value.
I've also see other serializers write a `"NaN"` value instead... but felt that `none` is easier to deal with than mixing types.
> fic(ifc): Fix for element quantities that contain nan values 
