specklesystems/specklepy

- speckle/api/operations.py
- speckle/logging/exceptions.py
- speckle/objects/base.py
- speckle/serialization/base_object_serializer.py
- speckle/transports/abstract_transport.py
- speckle/transports/memory.py
- speckle/transports/sqlite.py
This scaffolds transports and implements serialisation. It includes:
- `AbstractTransport` based on core's `ITransport`
- working memory transport and a start on the sqlite transport
- `Base` object class
- decomposition, serialisation, and deserialisation of `Base` objects
> 🥣 Serialisation and a start on transports

- speckle/api/credentials.py
- speckle/transports/sqlite.py
This adds some convenience models for accessing the local environment accounts.
```py
>>> from speckle.api.credentials import get_default_account, get_local_accounts
>>> get_local_accounts()
[Account(email: izzy@speckle.systems, server: https://staging.speckle.dev, isDefault: True), 
Account(email: izzy.lyseggen@gmail.com, server: https://staging.speckle.dev, isDefault: False)]
>>> get_default_account()
Account(email: izzy@speckle.systems, server: https://staging.speckle.dev, isDefault: True)
```
It also adds class objects for `Accounts`, `ServerInfo`, and `UserInfo`.
> 🙋‍♀️ Get local accounts

- speckle/api/client.py
- speckle/api/resources/commit.py
- speckle/api/resources/object.py
- speckle/objects/base.py
- speckle/serialization/base_object_serializer.py
Exposed more of the API functionality so people can have a good play with it.
This implements all the commit and object mutations.
> 🎁 More gql functions 

- README.md
Add some code examples and brief explanation of the current state of the package
> 📘 Basic documentation in readme

- speckle/transports/sqlite.py
> 💾 fix(sqlite): get correct db base path on macos

- speckle/api/client.py
remove protocol and trailing slash
closes #11
> 🧼 fix(client): sanitise host input

- speckle/api/models.py
- speckle/api/resources/commit.py
Add the new fields from specklesystems/speckle-server#64
> 🧜‍♀️ Update Commit Models & Queries

- speckle/objects/base.py
- speckle/serialization/base_object_serializer.py
> 🧨 Dynamic prop chunking

- .circleci/config.yml
- tests/conftest.py
> ✨ setting up ci: take 2 ✨

- .circleci/config.yml
> 🤖 ci: run tests for py 3.6 - 3.9

- speckle/api/credentials.py
- speckle/api/models.py
- speckle/api/resources/branch.py
- speckle/api/resources/server.py
- speckle/api/resources/stream.py
- speckle/api/resources/user.py
- tests/conftest.py
- tests/test_branch.py
- tests/test_commit.py
- tests/test_serialization.py
- tests/test_server.py
- tests/test_stream.py
- tests/test_user.py
brings this up to parity with speckle-sharp/core graphql client operations
also adds all the tests for these 
closes #25
> 🕸 More GQL Queries!

- speckle/api/operations.py
- speckle/api/resources/object.py
- speckle/objects/base.py
- speckle/objects/fakemesh.py
- speckle/objects/point.py
- speckle/objects/units.py
- speckle/serialization/base_object_serializer.py
- tests/conftest.py
- tests/test_objects.py
- tests/test_serialization.py
- add units property and helper to set it correctly (taken from core)
- add a `_detachable` list (similar to the `_chunkable` dict)b for predefining detachable attributes  
- step into the `data` field in server transport receive to parse the correct base subclass 
- tests to make sure this all works nicely
> 😇 Base Object Improvements

- speckle/api/resources/commit.py
to be consistent with the other connectors
> fix(commit): sourceapp change pyspeckle to python

- speckle/objects/base.py
just a bit of boyscout refactors on base model
﻿
> Base object code cleanup

- speckle/api/client.py
- speckle/serialization/base_object_serializer.py
i'm the queen of minor bug fixes 👑 
- register `branches` methods so they show up in intellisense
- generalise receiving chunk check so it consistently recomposes chunks from `sharp`
> 🐛 Even more bug fixes!

- speckle/serialization/base_object_serializer.py
default to using our obj for deserialisation
> fix(serialiser): import geometry objects

- speckle/objects/base.py
- speckle/objects/fakemesh.py
- speckle/objects/geometry.py
- speckle/serialization/base_object_serializer.py
- tests/test_serialization.py
some opti and fixes of embarassing bugs
> feat(serialisation): optimisations baBY

- speckle/api/operations.py
- speckle/serialization/base_object_serializer.py
- tests/test_serialization.py
allow providing transports to the serialize / deserialize functions
to see detaching and chunking
> feat(operations): better (de)serialize functions

- speckle/transports/server/__init__.py
- speckle/transports/server/batch_sender.py
- speckle/transports/server/server.py
@izzylys please review.
How should we approach the testing of the new functionality?
> ServerTransport: object batching and sending from multiple background threads

- .circleci/config.yml
- pyproject.toml
> Automated releases to PyPI

- specklepy/api/client.py
- specklepy/api/models.py
- specklepy/api/resources/server.py
- specklepy/transports/abstract_transport.py
- specklepy/transports/memory.py
- specklepy/transports/server/batch_sender.py
- specklepy/transports/server/server.py
- specklepy/transports/sqlite.py
WARNING: not compatible with older/current released speckle servers
> switched to diff endpoints for download/upload

- specklepy/api/credentials.py
for simple manual account addition
> fix(credentials): make some fields optional

- .circleci/config.yml
- pyproject.toml
- specklepy/api/credentials.py
- specklepy/transports/sqlite.py
> feat(credentials): read json files from local accts 

- poetry.lock
- pyproject.toml
- upgrade and change reqs in pyproject
> chore(build): update to gql 3.0.0a6

- specklepy/api/operations.py
- specklepy/transports/sqlite.py
> fix(sqlite): delay and try except transport init

- pyproject.toml
- specklepy/api/credentials.py
for the benefit of connectors eg blender
> feat(wrapper): add get acct helper

- specklepy/objects/geometry.py
> fix(objects): init polyline value w empty list

- specklepy/api/credentials.py
oopsie think this was a merge error
> fix(credentials): fix in get client

- specklepy/objects/base.py
- specklepy/objects/encoding.py
- specklepy/objects/geometry.py
- specklepy/objects/units.py
- specklepy/serialization/base_object_serializer.py
- tests/test_base.py
- tests/test_geometry.py
- tests/test_objects.py
Hi guys! I'm digging `pyspecklev2`! I mean, `specklepy`!!
I was playing around with integrating some custom object models through the Python client and was testing decoding a complex Brep to figure out how to reproduce it from some other object (you know... a honeybee model :bee: ).
Anyways, while I was messing with that I realised that there was no methods to deal with data chunks. This PR is meant to resolve this to the best of my understanding. Happy for any feedback/changes if it helps get this one through so I can go back to messing with honeybee schemas and speckle objects :raised_hands:
> Geometry chunks serialization

- specklepy/transports/server/batch_sender.py
for when send fails completely. previously user only got a
json decode error
closes #122
> fix(batch sender): improve error messages

- .circleci/config.yml
- .gitignore
- poetry.lock
- pyproject.toml
test result and coverage reporting in circleci
> add circle_ci reporting

- specklepy/objects/base.py
- specklepy/objects/other.py
- tests/test_transforms.py
replicated the behaviour from specklesystems/speckle-sharp#905
to be used in specklesystems/speckle-blender#60
> feat(objects): transforms and blocks!

- specklepy/objects/base.py
- specklepy/serialization/base_object_serializer.py
allow serialisation of null values and setting of none values on deserialisation
closes #145
> feat(serialisation): allow null values

- specklepy/api/client.py
Fixes #150 
@izzylys feel free to merge whenever
> surface server validation errors

- specklepy/api/credentials.py
closes #139
realised that this doesn't really apply to py since acct is set
automatically by looking for the right server url, but have made this
more explicit by making the acct and client "private"
> feat(wrapper): make acct/client private

- specklepy/api/client.py
- specklepy/transports/server/batch_sender.py
- tests/test_client_and_ops.py
adds catches in client and server transport for when the token is invalid
adds tests for this as well 
closes #155
> feat(client/ops): handle invalid token errors

- specklepy/objects/geometry.py
- tests/test_geometry.py
for my bff @AlanRynne bc ily <3
> feat(objects): add and test `Mesh.create()`

- specklepy/api/operations.py
- specklepy/api/resources/branch.py
- specklepy/api/resources/object.py
- specklepy/api/resources/server.py
- specklepy/api/resources/stream.py
- specklepy/api/resources/subscriptions.py
- specklepy/api/resources/user.py
- specklepy/logging/metrics.py
- specklepy/objects/base.py
- specklepy/objects/structural/analysis.py
- specklepy/objects/structural/geometry.py
- specklepy/objects/structural/loading.py
- specklepy/objects/structural/material.py
- specklepy/objects/structural/properties.py
- specklepy/objects/structural/results.py
- specklepy/serialization/base_object_serializer.py
- specklepy/transports/abstract_transport.py
- specklepy/transports/memory.py
- specklepy/transports/server/batch_sender.py
- specklepy/transports/server/server.py
closes specklesystems/admin#242
> chore: lgtm fixes

- specklepy/serialization/base_object_serializer.py
- tests/conftest.py
> fix/test(serialization): null values in dicts

- specklepy/objects/base.py
- specklepy/objects/fakemesh.py
- specklepy/serialization/base_object_serializer.py
- tests/conftest.py
- tests/test_base.py
note that this won't re-serialise dynamic members as enums.
they will come back as ints for consistency w sharp
closes 🃏 Enum serialisation bug #174
> feat(serialisation): enums

- specklepy/api/models.py
- specklepy/api/resources/stream.py
- specklepy/api/resources/user.py
- tests/test_stream.py
- tests/test_user.py
add `activity` method to `client.stream` and `client.user`
allow all available inputs including `cursor` as `datetime` objs
closes #172
> feat(client): stream and user activity

- specklepy/api/client.py
- specklepy/objects/encoding.py
- specklepy/objects/geometry.py
got some deserialisation fails from json dump from gh so doin this as an ez fix
> fix(geometry): int(index vals) for curve encoding

- specklepy/api/operations.py
- specklepy/api/resources/branch.py
- specklepy/api/speckle2schema.graphql
FIxes various documentation and source comment typos
> Fix various typos

- .circleci/config.yml
- .devcontainer/docker-compose.yaml
- .vscode/launch.json
- example/many_children.py
- example/using_speckle_base.py
- poetry.lock
- pyproject.toml
- specklepy/api/operations.py
- specklepy/api/resources/object.py
- specklepy/serialization/base_object_serializer.py
- specklepy/transports/sqlite.py
- tests/conftest.py
hacky workarond and example for #189
> SQLite write batching

- specklepy/logging/metrics.py
adds a constant id for unknown users
> feat(metrics): add ids for unknown users

- poetry.lock
- pyproject.toml
- specklepy/api/operations.py
- specklepy/api/resources/stream.py
- specklepy/objects/encoding.py
- specklepy/objects/geometry.py
- specklepy/objects/units.py
- specklepy/serialization/base_object_serializer.py
- tests/test_base.py
- tests/test_geometry.py
also includes breps overhaul to align with sharp 2.7.0 release
closes #191 
full test file
https://latest.speckle.dev/streams/2f855f4f2c/commits/716768709f
> feat(serialization): cache bases on deserialize 

- specklepy/logging/metrics.py
Reverts specklesystems/specklepy#204
> Revert "fix(metrics): log ex as debug for jupyter notebook"

- specklepy/api/resource.py
- specklepy/api/resources/stream.py
Just some minor typos
Typo-less code :)
2 API source comment changes. No source change
n/a
n/a
n/a
n/a
> Fix: misc. typos

- pyproject.toml
- src/specklepy/api/credentials.py
- src/specklepy/api/models.py
- src/specklepy/transports/abstract_transport.py
- src/specklepy/transports/sqlite.py
> make sure specklepy send works completely without disk write access

- .circleci/config.yml
> testing cimg/python311

- .circleci/config.yml
> ci(circleci): force integration test server to use localhost ipv4 adresses

- src/specklepy/serialization/base_object_serializer.py
- tests/test_traverse_value.py
> fix(BaseObjectSerializer): fix converting None in list to the string "None"

- src/specklepy/objects/base.py
- tests/unit/test_type_validation.py
> fix(typing-system): add set type into type validation

- src/specklepy/core/helpers/speckle_path_provider.py
- tests/unit/test_path.py
> feat(path-provider): add connector installation path helper

- utils/installer.py
Added `Installer.py` adapted from the version used in the Blender connector
Tested successfully with the Blender connector, see https://github.com/specklesystems/speckle-blender/pull/158
> Added Installer

- src/specklepy/objects/geometry.py
Pointcloud properties should be chunkable, otherwise the commit will fail.
> Fix Pointcloud bugs in geometry.py

- src/specklepy/api/resource.py
> fix(resource): make sure no threading contention with the client can happen

- src/specklepy/logging/metrics.py
- src/specklepy/transports/server/server.py
> 2.16 hotfixes

- src/specklepy/logging/metrics.py
> SDK Action metrics rename

- src/specklepy/logging/metrics.py
- src/specklepy/objects/GIS/CRS.py
- src/specklepy/objects/GIS/geometry.py
- src/specklepy/objects/GIS/layers.py
> 2.16 - add classes for Topography and Tables without geometry

- src/specklepy/objects/units.py
- tests/unit/test_unit_scaling.py
Added unit scale functions
see #290
> Unit scaling

- src/specklepy/transports/abstract_transport.py
- src/specklepy/transports/memory.py
- src/specklepy/transports/server/server.py
- src/specklepy/transports/sqlite.py
Pydantic is a validation and parsing library, its supposed to sit at the edge of apps, to make sure the data transferred in and out is valid. Its not meant to be a generic python base class.
> fix(AbstractTransport-and-subclasses): abstract transport and its subclasses should not be pydantic models

- src/specklepy/objects/GIS/layers.py
> add deprecated gis classes

- src/speckle_automate/automation_context.py
- src/specklepy/api/resources/commit.py
- src/specklepy/core/api/resources/commit.py
> fix(automate_sdk): make sure we throw for failed version create

- src/speckle_automate/automation_context.py
> pass branch name to commit.create

- src/speckle_automate/automation_context.py
- tests/intergration/speckle_automate/test_automation_context.py
> fix: automate sdk context view is a realative url

- src/specklepy/objects/other.py
I need a text object definition to render some texts on viewer with specklepy.
> Chore (Objects): Add text object definition

- docker-compose.yml
see https://github.com/specklesystems/speckle-sharp/pull/3017
> Pinned MinIO version for integration test docker compose

- docker-compose.yml
- src/specklepy/core/api/wrapper.py
- tests/intergration/test_wrapper.py
> update stream wrapper; add tests

- src/specklepy/core/api/models.py
- src/specklepy/core/api/resources/server.py
- tests/intergration/test_server.py
> add frontend2 property to ServerInfo

- src/specklepy/objects/geometry.py
See https://spockle.atlassian.net/browse/CNX-9014
This PR may also address #301 , once released we should ping them
> fix(objects): [CNX-9014] Fixed issue with Spiral turns not deserializing in SpecklePy

- src/speckle_automate/automation_context.py
- src/specklepy/core/api/models/current.py
> Main -> v3Dev

- src/specklepy/transports/server/server.py
> fix: server transport always accept text/plain

- src/specklepy/objects/geometry/mesh.py
> fix (specklepy): one-liner syntax fix

- src/specklepy/objects/geometry/__init__.py
- src/specklepy/objects/geometry/region.py
- src/specklepy/objects/tests/test_region.py
Replicate C# Region class: https://github.com/specklesystems/speckle-sharp-sdk/pull/241
"New Region class is a flat geometry represented by the boundary curve and inner loop curves, which hostApp turns into a planar filled geometry (or, Region). Hatch ("region" with a pattern or gradient fill) is a type of new Region class with a property "hasHatchPattern=true".
Currently the displayValue is a list of Meshes (for the apps that can triangulate meshes). We hope that in the future the Viewer can support this geometry and create a fill in the Viewer, without the need to generate and send an extra Mesh."
> add region class and tests

- src/specklepy/objects/geometry/__init__.py
- src/specklepy/objects/geometry/curve.py
- src/specklepy/objects/tests/test_curve.py
adds a curve class and the corresponding test
> feat(specklepy): curve object class

- src/specklepy/objects/other.py
> dont ignore render material props on send

- .github/workflows/publish.yml
updates publish.yml for on tag publish
> fix(specklepy): updates publish.yml

- .github/workflows/pr.yml
- src/specklepy/api/client.py
- src/specklepy/api/resources/__init__.py
- src/specklepy/api/resources/current/active_user_resource.py
- src/specklepy/api/resources/current/project_resource.py
- src/specklepy/api/resources/current/workspace_resource.py
- src/specklepy/core/api/client.py
- src/specklepy/core/api/inputs/project_inputs.py
- src/specklepy/core/api/inputs/user_inputs.py
- src/specklepy/core/api/models/current.py
- src/specklepy/core/api/resources/__init__.py
- src/specklepy/core/api/resources/current/active_user_resource.py
- src/specklepy/core/api/resources/current/project_invite_resource.py
- src/specklepy/core/api/resources/current/project_resource.py
- src/specklepy/core/api/resources/current/server_resource.py
- src/specklepy/core/api/resources/current/workspace_resource.py
- src/specklepy/logging/exceptions.py
- tests/integration/client/current/test_active_user_resource.py
- tests/integration/client/current/test_project_resource.py
- tests/integration/client/current/test_workspace_resource.py
Adds workspace resource
- `workspace.get`
- `workspace.get_projects`
Adds workspace related queries to active user
- `active_user.get_workspaces`
- `active_user.get_active_workspace`
Adds project queries
- `project.get_permissions`
- `project.create_in_workspace`
Fixed the problem @dogukankaratas with the integration tests running in github actions
> feat(api): Adds workspace related queries to active user resource and workspace resouse

- src/specklepy/core/api/inputs/project_inputs.py
- src/specklepy/core/api/models/current.py
- tests/integration/client/current/test_project_resource.py
> fix schema

- src/specklepy/core/api/inputs/user_inputs.py
- src/specklepy/core/api/models/current.py
- src/specklepy/core/api/resources/current/project_resource.py
- src/specklepy/core/api/resources/current/workspace_resource.py
- Fixed a couple gql models that weren't using `snake_case`
- Added workspace creation state
- Added `include_implicit_access`
> More tweaks

- src/specklepy/core/api/resources/current/active_user_resource.py
- src/specklepy/core/api/resources/current/workspace_resource.py
There was a mistake in the workspace get response handling
> fix(ap): fix mistake in workspace get response handling

- src/specklepy/core/api/enums.py
- tests/integration/client/current/test_project_invite_resource.py
- tests/integration/client/current/test_project_resource.py
> feat: add WORKSPACE visibility for projects

- .pre-commit-config.yaml
- docker-compose.yml
- src/specklepy/core/api/enums.py
- tests/integration/client/current/test_project_invite_resource.py
- tests/integration/client/current/test_project_resource.py
- tests/integration/client/deprecated/test_server.py
Similar fix as was applied to v3 https://github.com/specklesystems/specklepy/pull/421
> Fix(v2): Fix Workspace Visibility enum for Project queries

- src/specklepy/objects/__init__.py
- src/specklepy/objects/data_objects.py
- tests/objects/test_data_objects.py
adds BlenderObject to the DataObjects
> feat: BlenderObject

- pyproject.toml
> fix: specify what packages to include in the wheel

- .github/workflows/pr.yml
- .github/workflows/publish.yml
> fix(ci): Forward secret to publish job

- src/specklepy/core/api/wrapper.py
@bimgeek reported issues with using the stream wrapper on the latest version of specklepy...
I found we were using a very old bit of logic to fetch the model name...
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[6], line 1
----> 1 wrapper = StreamWrapper(ODA_MODEL_URL)
2 client = wrapper.get_client()
3 ref_obj = client.version.get_versions(wrapper.model_id, wrapper.stream_id, limit=1).items[0].referenced_object
File c:\Users\mucah\Github\oda-compare.venv\Lib\site-packages\specklepy\api\wrapper.py:46, in StreamWrapper.init(self, url)
45 def init(self, url: str) -> None:
---> 46     super().init(url=url)
File c:\Users\mucah\Github\oda-compare.venv\Lib\site-packages\specklepy\ …
```
> fix(specklepy): Fix stream wrapper client call
